package chunks

// GetReactChunks returns the list of React chunk filenames
// This is auto-generated by scripts/extract-chunks.js after build
func GetReactChunks() []string {
	return []string{
		"chunk-ZF6O5QYW.js",
		"chunk-GPTWFTAR.js",
		"chunk-NM6J3ND7.js",
	}
}
