package tools

var ToolsList = []Tool{
	{
		ID:          "json-utilities",
		Title:       "JSON Formatter, Validator and Linter | Online Free DevTools by Hexmos",
		Name:        "JSON Utilities",
		Path:        "/freedevtools/t/json-utilities/",
		Description: "Format, validate, and lint JSON online for free with Hexmos Free DevTools. Enjoy multiple indentation options and real-time validation in an ad-free environment.",
		Category:    "Developer Tools",
		Icon:        "🧰",
		ThemeColor:  "#14b8a6",
		Canonical:   "https://hexmos.com/freedevtools/t/json-utilities/",
		Keywords: []string{
			"json utilities",
			"json tools",
			"json formatter",
			"json prettifier",
			"json beautifier",
			"json minifier",
			"json validator",
			"json fixer",
			"json corrector",
			"developer tools",
			"api tools",
			"online json editor",
		},
		Features: []string{
			"Format and beautify JSON",
			"Validate JSON structure",
			"Auto-correct invalid JSON",
			"Multiple indentation options",
			"Real-time validation and feedback",
			"Instant error detection",
			"Copy to clipboard",
		},
		OgImage:        "https://hexmos.com/freedevtools/public/tool-banners/json-utilities-banner.png",
		TwitterImage:   "https://hexmos.com/freedevtools/public/tool-banners/json-utilities-banner.png",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "json-prettifier",
		Title:       "JSON Formatter, Validator and Linter | Online Free DevTools by Hexmos",
		Name:        "JSON Prettifier",
		Path:        "/freedevtools/t/json-prettifier/",
		Description: "Format, validate, and lint JSON online for free with Hexmos Free DevTools. Enjoy multiple indentation options and real-time validation in an ad-free environment.",
		Category:    "Developer Tools",
		Icon:        "📄",
		ThemeColor:  "#10b981",
		Canonical:   "https://hexmos.com/freedevtools/t/json-prettifier/",
		Keywords: []string{
			"JSON online formatter",
			"JSON online validator",
			"JSON online linter",
			"JSON online",
			"Best JSON formatter",
		},
		Features: []string{
			"JSON formatting",
			"JSON minification",
			"JSON validation",
			"Multiple indentation options",
			"Real-time validation",
			"Copy to clipboard",
		},
		OgImage:        "https://hexmos.com/freedevtools/public/tool-banners/json-prettifier-banner.png",
		TwitterImage:   "https://hexmos.com/freedevtools/public/tool-banners/json-prettifier-banner.png",
		VariationOf:    "json-utilities",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "json-validator",
		Title:       "JSON Validator - Check & Validate Your JSON Online",
		Name:        "JSON Validator",
		Path:        "/freedevtools/t/json-validator/",
		Description: "Validate your JSON instantly. Detect errors, check formatting, and ensure your JSON is well-formed.",
		Category:    "Developer Tools",
		Icon:        "✅",
		ThemeColor:  "#f59e0b",
		Canonical:   "https://hexmos.com/freedevtools/t/json-validator/",
		Keywords: []string{
			"json validator",
			"json check",
			"validate json",
			"developer tools",
		},
		Features: []string{
			"Validate JSON structure",
			"Detect formatting errors",
			"Real-time error messages",
			"Copy to clipboard",
		},
		OgImage:        "https://hexmos.com/freedevtools/public/tool-banners/json-validator-banner.png",
		TwitterImage:   "https://hexmos.com/freedevtools/public/tool-banners/json-validator-banner.png",
		VariationOf:    "json-utilities",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "json-fixer",
		Title:       "JSON Fixer - Automatically Correct JSON Errors",
		Name:        "JSON Fixer",
		Path:        "/freedevtools/t/json-fixer/",
		Description: "Automatically fix invalid JSON data. Correct errors, format it properly, and get clean JSON instantly.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/json-fixer/",
		Features: []string{
			"Auto-correct invalid JSON",
			"Format JSON properly",
			"Real-time feedback",
			"Copy fixed JSON",
		},
		OgImage:        "https://hexmos.com/freedevtools/public/tool-banners/json-fixer-banner.png",
		TwitterImage:   "https://hexmos.com/freedevtools/public/tool-banners/json-fixer-banner.png",
		VariationOf:    "json-utilities",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "password-generator",
		Title:       "Secure, Strong & Random Password Generator | Online Free DevTools by Hexmos",
		Name:        "Password Generator",
		Path:        "/freedevtools/t/password-generator/",
		Description: "Generate secure passwords instantly with Hexmos Free DevTools. Choose quick presets, customize password type, length, and characters for strong, random passwords.",
		Category:    "Security Tools",
		Icon:        "�",
		ThemeColor:  "#6366f1",
		Canonical:   "https://hexmos.com/freedevtools/t/password-generator/",
		Keywords: []string{
			"password generator",
			"secure password generator",
			"random password generator",
			"strong password generator",
			"free password generator",
			"online password generator",
			"custom password generator",
			"password creator tool",
			"password maker online",
			"cybersecurity tools",
		},
		Features: []string{
			"Quick presets for easy selection",
			"Password types: word-based or character-based",
			"Customizable password length",
			"Multiple character set options",
			"Readable password generation",
			"Instant password creation",
			"Copy to clipboard",
			"Real-time password strength indicator",
		},
		OgImage:        "https://hexmos.com/freedevtools/public/tool-banners/password-generator-banner.png",
		TwitterImage:   "https://hexmos.com/freedevtools/public/tool-banners/password-generator-banner.png",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "dockerfile-linter",
		Title:       "Dockerfile Linter and Validator | Online Free DevTools by Hexmos",
		Name:        "Dockerfile Linter",
		Path:        "/freedevtools/t/dockerfile-linter/",
		Description: "Comprehensive Dockerfile linter. Analyze, validate, and optimize Dockerfiles for syntax errors, security risks, performance issues, and best practices.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#2496ed",
		Canonical:   "https://hexmos.com/freedevtools/t/dockerfile-linter/",
		Keywords: []string{
			"dockerfile linter",
			"docker linter",
			"dockerfile validator",
			"docker security",
			"dockerfile analyzer",
			"container security",
			"docker best practices",
			"dockerfile syntax",
			"dockerfile checker",
			"developer tools",
		},
		Features: []string{
			"Syntax validation and error detection",
			"Security vulnerability analysis",
			"Performance optimization suggestions",
			"Docker best practices enforcement",
			"Real-time feedback with explanations",
			"Copy results to clipboard",
		},
		OgImage:        "https://hexmos.com/freedevtools/public/tool-banners/dockerfile-linter-banner.png",
		TwitterImage:   "https://hexmos.com/freedevtools/public/tool-banners/dockerfile-linter-banner.png",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "date-time-converter",
		Title:       "Date Time Converter | Online Free DevTools by Hexmos",
		Name:        "Date Time Converter",
		Path:        "/freedevtools/t/date-time-converter/",
		Description: "Free online Date Time Converter by Hexmos. Instantly convert UTC, ISO, Unix timestamps, and more. Paste or pick a date to see all formats at once, no signup needed.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/date-time-converter/",
		Keywords: []string{
			"datetime converter",
			"date converter",
			"time converter",
			"timestamp converter",
			"unix timestamp",
			"online date converter",
			"free date converter",
			"timestamp converter online",
		},
		Features: []string{
			"Convert between UTC, ISO, Unix, and other date/time formats",
			"Date and time picker integration",
			"Handles timestamps, ISO strings, and custom formats",
			"Shows all common formats at a glance",
		},
		OgImage:        "https://hexmos.com/freedevtools/public/tool-banners/date-time-converter-banner.png",
		TwitterImage:   "https://hexmos.com/freedevtools/public/tool-banners/date-time-converter-banner.png",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "openai-token-counter",
		Title:       "OpenAI Token Counter - Count GPT Tokens | Online Free DevTools by Hexmos",
		Name:        "OpenAI Token Counter",
		Path:        "/freedevtools/t/openai-token-counter/",
		Description: "Count OpenAI tokens instantly with our free online token counter. Calculate GPT-5, GPT-4, GPT-3.5, o1 tokens.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/openai-token-counter/",
		Keywords: []string{
			"openai token counter",
			"gpt token counter",
			"openai api token calculator",
			"gpt-4 token counter",
			"gpt-5 token counter",
			"tiktoken counter",
		},
		Features: []string{
			"Count tokens for all OpenAI models (GPT-4, GPT-3.5, o1, o3)",
			"Real-time token calculation using tiktoken",
			"Support for latest models including GPT-5 and embedding models",
			"Context limit tracking and usage percentage",
			"Browser-based processing - your data stays private",
		},
		OgImage:        "https://hexmos.com/freedevtools/public/tool-banners/openai-token-counter.png",
		TwitterImage:   "https://hexmos.com/freedevtools/public/tool-banners/openai-token-counter.png",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "anthropic-token-counter",
		Title:       "Anthropic Token Counter - Count Claude Tokens | Online Free DevTools by Hexmos",
		Name:        "Anthropic Token Counter",
		Path:        "/freedevtools/t/anthropic-token-counter/",
		Description: "Count Anthropic tokens instantly with our free online Claude token counter. Calculate Claude-3.5, Claude-3, Opus tokens.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/anthropic-token-counter/",
		Keywords: []string{
			"anthropic token counter",
			"claude token counter",
			"anthropic api token calculator",
			"claude-3 token counter",
			"claude-4 token counter",
			"claude token calculator",
		},
		Features: []string{
			"Count tokens for all Claude models (Opus, Sonnet, Haiku)",
			"Real-time token calculation using official Anthropic tokenizers",
			"Support for latest models including Claude-3.5 and Claude-4",
			"Context limit tracking and usage percentage calculation",
			"Browser-based processing - your data stays private",
		},
		OgImage:        "https://hexmos.com/freedevtools/public/tool-banners/anthropic-token-counter.png",
		TwitterImage:   "https://hexmos.com/freedevtools/public/tool-banners/anthropic-token-counter.png",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "json-to-csv-converter",
		Title:       "JSON to CSV Converter - Transform JSON Data | Online Free DevTools by Hexmos",
		Name:        "Json To Csv Converter",
		Path:        "/freedevtools/t/json-to-csv-converter/",
		Description: "Convert JSON data to CSV format instantly. Transform arrays of objects to spreadsheet-ready CSV files with real-time preview and advanced formatting options.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/json-to-csv-converter/",
		Keywords: []string{
			"json-to-csv-converter",
			"developer tools",
			"csv converter",
			"json converter",
			"data transformation",
			"json to spreadsheet",
		},
		Features: []string{
			"Real-time JSON to CSV conversion",
			"Flatten nested JSON objects",
			"Download CSV files instantly",
			"Handle arrays and single objects",
			"Empty field customization",
			"Copy to clipboard functionality",
			"Browser-based processing - data stays private",
		},
		OgImage:        "https://hexmos.com/freedevtools/public/tool-banners/json-utilities-banner.png",
		TwitterImage:   "https://hexmos.com/freedevtools/public/tool-banners/json-utilities-banner.png",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "image-to-base64",
		Title:       "Image to Base64 Converter - Encode Images Instantly | Online Free DevTools by Hexmos",
		Name:        "Image To Base64",
		Path:        "/freedevtools/t/image-to-base64/",
		Description: "Convert images to Base64 format instantly with our free online converter. Upload PNG, JPG, GIF, WebP images and get Base64 string, HTML img tag, CSS background code. Secure browser-based processing.",
		Category:    "Developer Tools",
		Icon:        "🖼️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/image-to-base64/",
		Keywords: []string{
			"image to base64 converter",
			"base64 image encoder",
			"convert image to base64",
			"base64 image generator",
			"online image encoder",
			"image data uri converter",
			"png to base64",
			"jpg to base64",
		},
		Features: []string{
			"Convert images to Base64 format instantly",
			"Support for PNG, JPG, GIF, WebP, SVG formats",
			"Generate HTML img tags and CSS background code",
			"Drag-and-drop file upload interface",
			"Browser-based processing - no server uploads",
			"Real-time conversion with copy functionality",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/image-to-base64-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/image-to-base64-banner.png",
		DatePublished:   "2025-09-11",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "jwt-parser",
		Title:       "JWT Parser - Decode JSON Web Tokens Online | Online Free DevTools by Hexmos",
		Name:        "JWT Parser",
		Path:        "/freedevtools/t/jwt-parser/",
		Description: "Parse and decode JWT tokens instantly with our free online JWT parser. Decode header, payload, and signature from JSON Web Tokens with real-time validation. Secure browser-based processing.",
		Category:    "Developer Tools",
		Icon:        "🔐",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/jwt-parser/",
		Keywords: []string{
			"jwt parser",
			"jwt decoder",
			"json web token parser",
			"decode jwt online",
			"jwt token decoder",
			"free jwt parser",
			"online jwt decoder",
			"jwt validation tool",
		},
		Features: []string{
			"Parse JWT tokens instantly with real-time decoding",
			"Decode header, payload, and signature sections separately",
			"Real-time JWT validation and error detection",
			"Sample JWT tokens for testing and learning",
			"Copy decoded sections to clipboard individually",
			"Browser-based processing - tokens never leave your device",
			"Support for all JWT algorithms and formats",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/jwt-parser-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/jwt-parser-banner.png",
		DatePublished:   "2025-09-11",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "yaml-to-json",
		Title:       "YAML to JSON Converter - Transform YAML Online | Online Free DevTools by Hexmos",
		Name:        "YAML to JSON Converter",
		Path:        "/freedevtools/t/yaml-to-json/",
		Description: "Convert YAML to JSON format instantly with our free online converter. Transform YAML configuration files to JSON with real-time validation and formatting. Secure browser-based processing.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/yaml-to-json/",
		Keywords: []string{
			"yaml to json converter",
			"convert yaml to json online",
			"yaml json converter free",
			"yaml to json online tool",
			"transform yaml data json",
			"yaml configuration converter",
			"online yaml parser",
		},
		Features: []string{
			"Real-time YAML to JSON conversion",
			"Support for multi-document YAML files",
			"Comprehensive error handling and validation",
			"Sample YAML data for testing",
			"Copy to clipboard functionality",
			"Browser-based processing - data stays private",
			"Support for all YAML syntax features",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/yaml-to-json-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/yaml-to-json-banner.png",
		DatePublished:   "2025-09-11",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "uuid-generator",
		Title:       "UUID Generator - Generate Secure UUIDs Online | Online Free DevTools by Hexmos",
		Name:        "UUID Generator",
		Path:        "/freedevtools/t/uuid-generator/",
		Description: "Generate secure UUIDs instantly with our free online UUID generator. Create random v4 UUIDs, timestamp-based v1 UUIDs, or special nil/max UUIDs. Bulk generation and analysis tools included.",
		Category:    "Developer Tools",
		Icon:        "🆔",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/uuid-generator/",
		Keywords: []string{
			"uuid generator",
			"guid generator",
			"unique identifier generator",
			"random uuid generator",
			"uuid v4 generator",
			"bulk uuid generator",
			"online uuid generator",
			"free uuid generator",
		},
		Features: []string{
			"Generate UUID v1, v4, nil, and max versions",
			"Bulk UUID generation (up to 1000 at once)",
			"UUID format customization (uppercase, no dashes)",
			"Real-time UUID analysis and validation",
			"Copy individual or bulk UUIDs to clipboard",
			"Browser-based processing - no server uploads",
			"Support for all standard UUID formats and variants",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/uuid-generator-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/uuid-generator-banner.png",
		DatePublished:   "2025-09-11",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "svg-viewer",
		Title:       "SVG Viewer - View & Analyze SVG Files Online | Online Free DevTools by Hexmos",
		Name:        "SVG Viewer",
		Path:        "/freedevtools/t/svg-viewer/",
		Description: "View and analyze SVG files instantly with our free online SVG viewer. Upload SVG files or paste SVG code to visualize, edit, and download. Real-time preview with dimension analysis.",
		Category:    "Developer Tools",
		Icon:        "�️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/svg-viewer/",
		Keywords: []string{
			"svg viewer",
			"svg file viewer",
			"view svg online",
			"svg preview tool",
			"svg analyzer",
			"svg code viewer",
			"online svg editor",
			"svg dimension checker",
		},
		Features: []string{
			"Upload SVG files or paste SVG code directly",
			"Real-time SVG preview and rendering",
			"SVG dimension and file size analysis",
			"Download processed SVG files",
			"Fullscreen preview mode",
			"Browser-based processing - data stays private",
			"Support for all SVG elements and attributes",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/svg-viewer-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/svg-viewer-banner.png",
		DatePublished:   "2025-09-11",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "sql-minifier",
		Title:       "SQL Minifier - Optimize SQL Queries Online | Online Free DevTools by Hexmos",
		Name:        "SQL Minifier",
		Path:        "/freedevtools/t/sql-minifier/",
		Description: "Minify SQL queries instantly with our free online SQL minifier. Remove comments, extra spaces, and optimize SQL formatting for better performance and smaller file sizes. Secure browser-based processing.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/sql-minifier/",
		Keywords: []string{
			"sql minifier",
			"sql optimizer",
			"minify sql online",
			"sql code minifier",
			"compress sql queries",
			"sql formatter",
			"optimize sql code",
			"remove sql comments",
		},
		Features: []string{
			"Minify SQL queries instantly with real-time processing",
			"Remove comments and extra whitespace from SQL code",
			"Preserve or strip SQL comments based on preferences",
			"Calculate compression ratio and size savings",
			"Support for all SQL dialects and database systems",
			"Browser-based processing - queries never leave your device",
			"Copy minified SQL to clipboard with one click",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/sql-minifier-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/sql-minifier-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "rgb-to-hex",
		Title:       "RGB to HEX Converter - Convert RGB Colors Online | Online Free DevTools by Hexmos",
		Name:        "RGB to HEX Converter",
		Path:        "/freedevtools/t/rgb-to-hex/",
		Description: "Convert RGB color values to HEX format instantly with our free online RGB to HEX converter. Transform red, green, blue values to hexadecimal color codes with real-time preview and multiple format outputs.",
		Category:    "Developer Tools",
		Icon:        "🎨",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/rgb-to-hex/",
		Keywords: []string{
			"rgb to hex converter",
			"rgb hex converter",
			"convert rgb to hex",
			"color converter online",
			"rgb to hexadecimal",
			"css color converter",
			"rgb hex color tool",
			"hex color generator",
		},
		Features: []string{
			"Real-time RGB to HEX conversion",
			"Interactive color preview",
			"Multiple format outputs (CSS, HSL, Swift, Android)",
			"Bidirectional conversion (RGB ↔ HEX)",
			"Copy to clipboard functionality",
			"Mobile development color codes",
			"Browser-based processing - no server uploads",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/rgb-to-hex-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/rgb-to-hex-banner.png",
		DatePublished:   "2025-09-11",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "diff-checker",
		Title:       "Diff Checker - Compare Text & Code Online | Online Free DevTools by Hexmos",
		Name:        "Diff Checker",
		Path:        "/freedevtools/t/diff-checker/",
		Description: "Compare text and code differences instantly with our free online diff checker. Visualize changes character by character, word by word, or line by line with advanced comparison options and unified diff export.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/diff-checker/",
		Keywords: []string{
			"diff checker",
			"text comparison tool",
			"code diff online",
			"compare text files",
			"difference checker",
			"file comparison tool",
			"online diff tool",
			"text diff viewer",
		},
		Features: []string{
			"Real-time text and code comparison",
			"Multiple comparison modes (character, word, line, sentence)",
			"Ignore case and whitespace options",
			"Visual diff highlighting with color coding",
			"Unified diff export for version control",
			"Statistical analysis of changes",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/diff-checker-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/diff-checker-banner.png",
		DatePublished:   "2025-09-11",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "regex-tester",
		Title:       "Regex Tester - Test Regular Expressions Online | Online Free DevTools by Hexmos",
		Name:        "Regex Tester",
		Path:        "/freedevtools/t/regex-tester/",
		Description: "Test regular expressions instantly with our free online regex tester. Validate patterns, find matches, and debug regex with real-time highlighting and detailed match information. Secure browser-based processing.",
		Category:    "Developer Tools",
		Icon:        "🔍",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/regex-tester/",
		Keywords: []string{
			"regex tester",
			"regular expression tester",
			"regex validator",
			"pattern matcher",
			"regex debugger",
			"online regex tool",
			"regex pattern tester",
			"javascript regex tester",
		},
		Features: []string{
			"Test regex patterns instantly with real-time validation",
			"Visual match highlighting in test strings",
			"Support for all JavaScript regex flags (g, i, m, s, u, y)",
			"Detailed match information and capture groups",
			"Error detection and validation feedback",
			"Sample regex patterns for learning",
			"Browser-based processing - patterns never leave your device",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/regex-tester-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/regex-tester-banner.png",
		DatePublished:   "2025-09-11",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "query-params-to-json",
		Title:       "Query Params to JSON Converter - Parse URL Parameters | Online Free DevTools by Hexmos",
		Name:        "Query Params To JSON",
		Path:        "/freedevtools/t/query-params-to-json/",
		Description: "Convert URL query parameters to JSON format instantly with our free online converter. Parse query strings from URLs, form data, and API endpoints into structured JSON objects with real-time validation.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/query-params-to-json/",
		Keywords: []string{
			"query params to json converter",
			"url parameters to json",
			"query string parser",
			"url query converter",
			"parse query parameters",
			"query string to json online",
			"url parameter parser",
			"query params decoder",
		},
		Features: []string{
			"Convert URL query parameters to JSON format",
			"Parse complex nested query structures",
			"Handle arrays and special characters in URLs",
			"Real-time conversion with validation",
			"Support for encoded and decoded URLs",
			"Copy JSON output to clipboard",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/query-params-to-json-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/query-params-to-json-banner.png",
		DatePublished:   "2025-09-13",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "lorem-ipsum-generator",
		Title:       "Lorem Ipsum Generator - Create Placeholder Text | Free Online Tool",
		Name:        "Lorem Ipsum Generator",
		Path:        "/freedevtools/t/lorem-ipsum-generator/",
		Description: "Generate random Lorem Ipsum placeholder text instantly with our free online generator. Create words, sentences, or paragraphs for design mockups, layouts, and content testing. Fast, customizable, and ad-free.",
		Category:    "Developer Tools",
		Icon:        "📝",
		ThemeColor:  "#8b5cf6",
		Canonical:   "https://hexmos.com/freedevtools/t/lorem-ipsum-generator/",
		Keywords: []string{
			"lorem ipsum generator",
			"placeholder text generator",
			"dummy text generator",
			"fake text generator",
			"lorem ipsum online",
		},
		Features: []string{
			"Generate words, sentences, or paragraphs",
			"HTML format output option",
			"Start with classic Lorem Ipsum text",
			"Customizable amount (1-99 units)",
			"Instant copy to clipboard",
			"Mobile responsive interface",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/lorem-ipsum-generator-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/lorem-ipsum-generator-banner.png",
		DatePublished:   "2025-09-13",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "json-to-yaml",
		Title:       "JSON to YAML Converter - Transform JSON Online | Online Free DevTools by Hexmos",
		Name:        "JSON to YAML Converter",
		Path:        "/freedevtools/t/json-to-yaml/",
		Description: "Convert JSON to YAML format instantly with our free online converter. Transform JSON configuration files to YAML with real-time validation and formatting. Secure browser-based processing.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/json-to-yaml/",
		Keywords: []string{
			"json to yaml converter",
			"convert json to yaml online",
			"json yaml converter free",
			"json to yaml online tool",
			"transform json data yaml",
			"json configuration converter",
			"online json parser",
		},
		Features: []string{
			"Real-time JSON to YAML conversion",
			"Support for nested JSON objects and arrays",
			"Comprehensive error handling and validation",
			"Sample JSON data for testing",
			"Copy to clipboard functionality",
			"Browser-based processing - data stays private",
			"Support for all JSON syntax features",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/json-to-yaml-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/json-to-yaml-banner.png",
		DatePublished:   "2025-09-13",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "hash-generator",
		Title:       "Hash Generator - Generate Secure Hashes Online | Online Free DevTools by Hexmos",
		Name:        "Hash Generator",
		Path:        "/freedevtools/t/hash-generator/",
		Description: "Generate secure hashes instantly with our free online hash generator. Create SHA-256, SHA-512, MD5, PBKDF2, and HMAC hashes with customizable options for security and development needs.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/hash-generator/",
		Keywords: []string{
			"hash generator",
			"sha256 generator",
			"sha512 generator",
			"md5 generator",
			"pbkdf2 generator",
			"hmac generator",
			"cryptographic hash",
			"secure hash online",
			"password hash generator",
			"data integrity hash",
		},
		Features: []string{
			"Multiple hash algorithms (SHA-256, SHA-512, MD5, PBKDF2, HMAC)",
			"Customizable encoding options (Hex, Base64, Latin1)",
			"PBKDF2 with configurable iterations and salt",
			"HMAC with custom secret keys",
			"Real-time hash generation",
			"Copy to clipboard functionality",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/hash-generator-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/hash-generator-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "har-file-viewer",
		Title:       "HAR File Viewer - Analyze HTTP Archive Files Online | Online Free DevTools by Hexmos",
		Name:        "HAR File Viewer",
		Path:        "/freedevtools/t/har-file-viewer/",
		Description: "Analyze HTTP Archive (HAR) files instantly with our free online HAR viewer. Debug network traffic, analyze web performance, and examine HTTP requests with detailed waterfall charts and table views.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/har-file-viewer/",
		Keywords: []string{
			"har file viewer",
			"http archive viewer",
			"har analyzer",
			"network traffic analyzer",
			"web performance analyzer",
			"har file parser",
			"http request analyzer",
			"waterfall chart viewer",
			"network debugging tool",
			"web developer tools",
		},
		Features: []string{
			"Upload and analyze HAR files instantly",
			"Interactive waterfall charts for performance analysis",
			"Detailed table view with sorting and filtering",
			"Filter by content type (XHR, JS, CSS, Images, etc.)",
			"Status code filtering and error highlighting",
			"Request/response headers inspection",
			"Browser-based processing - files never leave your device",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/har-file-viewer-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/har-file-viewer-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "env-to-netlify-toml",
		Title:       "Env to Netlify TOML Converter - Transform Environment Variables | Online Free DevTools by Hexmos",
		Name:        "Env to Netlify TOML Converter",
		Path:        "/freedevtools/t/env-to-netlify-toml/",
		Description: "Convert .env files to Netlify TOML format instantly with our free online converter. Transform environment variables for Netlify deployment configuration with proper TOML syntax and validation.",
		Category:    "Developer Tools",
		Icon:        "⚙️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/env-to-netlify-toml/",
		Keywords: []string{
			"env to netlify toml converter",
			"environment variables converter",
			"netlify toml generator",
			"env file converter",
			"netlify deployment config",
			"toml converter online",
			"netlify environment variables",
			"env to toml converter",
			"netlify config generator",
			"deployment environment setup",
		},
		Features: []string{
			"Real-time .env to netlify.toml conversion",
			"Support for environment-specific variables",
			"Proper TOML syntax formatting",
			"Handle quoted and unquoted values",
			"Context-specific variable organization",
			"Copy to clipboard functionality",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/env-to-netlify-toml-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/env-to-netlify-toml-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "csv-to-json",
		Title:       "CSV to JSON Converter - Transform CSV Data Online | Online Free DevTools by Hexmos",
		Name:        "CSV to JSON Converter",
		Path:        "/freedevtools/t/csv-to-json/",
		Description: "Convert CSV files to JSON format instantly with our free online converter. Upload CSV files or paste CSV data to transform into structured JSON objects with customizable formatting options.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/csv-to-json/",
		Keywords: []string{
			"csv to json converter",
			"convert csv to json online",
			"csv json converter free",
			"csv to json online tool",
			"transform csv data json",
			"csv file converter",
			"online csv parser",
			"csv json transformation",
			"data conversion tool",
			"spreadsheet to json",
		},
		Features: []string{
			"Real-time CSV to JSON conversion",
			"Upload CSV files or paste CSV data",
			"Customizable key formatting (lowercase option)",
			"Drag and drop file upload support",
			"Handle different CSV delimiters and formats",
			"Copy to clipboard functionality",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/csv-to-json-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/csv-to-json-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "css-units-converter",
		Title:       "CSS Units Converter - Convert px, rem, vw, vh Online | Online Free DevTools by Hexmos",
		Name:        "CSS Units Converter",
		Path:        "/freedevtools/t/css-units-converter/",
		Description: "Convert CSS units instantly with our free online converter. Transform pixels to rem, viewport units (vw, vh, vmin, vmax), and more with real-time conversion and responsive design calculations.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/css-units-converter/",
		Keywords: []string{
			"css units converter",
			"px to rem converter",
			"viewport units converter",
			"css unit calculator",
			"responsive design converter",
			"px to vw converter",
			"rem to px converter",
			"css measurement converter",
			"web design units",
			"css length units",
		},
		Features: []string{
			"Convert between px, rem, vw, vh, vmin, vmax units",
			"Real-time conversion with instant results",
			"Responsive design calculations",
			"Container dimension inputs for viewport units",
			"Bidirectional unit conversion",
			"Copy results to clipboard",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/css-units-converter-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/css-units-converter-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "base64-utilities",
		Title:       "Base64 Encoder/Decoder - Encode & Decode Text Online | Online Free DevTools by Hexmos",
		Name:        "Base64 Utilities",
		Path:        "/freedevtools/t/base64-utilities/",
		Description: "Encode and decode text to/from Base64 format instantly with our free online Base64 encoder/decoder. Perfect for data transmission, storage, and web development with real-time conversion.",
		Category:    "Developer Tools",
		Icon:        "🔒",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/base64-utilities/",
		Keywords: []string{
			"base64 utilities",
			"base64 tools",
			"base64 encoder",
			"base64 decoder",
			"base64 converter",
			"encode text to base64",
			"decode base64 to text",
			"base64 online tool",
			"data encoding tool",
			"text encoder decoder",
			"base64 conversion",
			"safe data transmission",
		},
		Features: []string{
			"Real-time Base64 encoding and decoding",
			"Bidirectional conversion (encode/decode)",
			"Support for text and binary data encoding",
			"Instant error detection for invalid Base64",
			"Copy to clipboard functionality",
			"Mobile responsive interface",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/base64-encoder-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/base64-encoder-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "base64-encoder",
		Title:       "Base64 Encoder - Encode Text to Base64 Online | Online Free DevTools by Hexmos",
		Name:        "Base64 Encoder",
		Path:        "/freedevtools/t/base64-encoder/",
		Description: "Encode text to Base64 format instantly with our free online Base64 encoder. Perfect for data transmission, storage, and web development with real-time encoding.",
		Category:    "Developer Tools",
		Icon:        "📤",
		ThemeColor:  "#10b981",
		Canonical:   "https://hexmos.com/freedevtools/t/base64-encoder/",
		Keywords: []string{
			"base64 encoder",
			"encode to base64",
			"text to base64",
			"base64 encoding online",
			"data encoder",
			"text encoder",
			"base64 converter",
		},
		Features: []string{
			"Real-time Base64 encoding",
			"Support for text and binary data",
			"Instant encoding results",
			"Copy to clipboard functionality",
			"Mobile responsive interface",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/base64-encode-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/base64-encode-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		VariationOf:     "base64-utilities",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "base64-decoder",
		Title:       "Base64 Decoder - Decode Base64 to Text Online | Online Free DevTools by Hexmos",
		Name:        "Base64 Decoder",
		Path:        "/freedevtools/t/base64-decoder/",
		Description: "Decode Base64 to text format instantly with our free online Base64 decoder. Perfect for data retrieval and web development with real-time decoding and error detection.",
		Category:    "Developer Tools",
		Icon:        "📥",
		ThemeColor:  "#f59e0b",
		Canonical:   "https://hexmos.com/freedevtools/t/base64-decoder/",
		Keywords: []string{
			"base64 decoder",
			"decode base64",
			"base64 to text",
			"base64 decoding online",
			"data decoder",
			"text decoder",
			"base64 converter",
		},
		Features: []string{
			"Real-time Base64 decoding",
			"Instant error detection for invalid Base64",
			"Support for various Base64 formats",
			"Copy to clipboard functionality",
			"Mobile responsive interface",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/base64-decoder-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/base64-decoder-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		VariationOf:     "base64-utilities",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "css-inliner-for-email",
		Title:       "CSS Inliner for Email - Convert CSS to Inline Styles | Online Free DevTools by Hexmos",
		Name:        "CSS Inliner for Email",
		Path:        "/freedevtools/t/css-inliner-for-email/",
		Description: "Convert CSS styles to inline styles for email HTML instantly with our free CSS inliner. Perfect for email templates, newsletters, and ensuring cross-client compatibility with real-time conversion.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/css-inliner-for-email/",
		Keywords: []string{
			"css inliner",
			"email css inliner",
			"css to inline styles",
			"email template tool",
			"inline css converter",
			"email html optimizer",
			"css email tool",
			"newsletter css inliner",
			"html email converter",
			"email css generator",
		},
		Features: []string{
			"Convert CSS styles to inline HTML attributes",
			"Real-time CSS to inline conversion",
			"Email client compatibility optimization",
			"Support for complex CSS selectors",
			"HTML and CSS validation",
			"Copy to clipboard functionality",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/css-inliner-for-email-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/css-inliner-for-email-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "curl-to-js-fetch",
		Title:       "cURL to JavaScript Fetch Converter - Convert cURL Commands | Online Free DevTools by Hexmos",
		Name:        "cURL to JavaScript Fetch",
		Path:        "/freedevtools/t/curl-to-js-fetch/",
		Description: "Convert cURL commands to JavaScript fetch API code instantly with our free online converter. Transform command-line HTTP requests into modern JavaScript fetch calls with real-time conversion.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/curl-to-js-fetch/",
		Keywords: []string{
			"curl to javascript",
			"curl to fetch converter",
			"curl converter",
			"javascript fetch generator",
			"http request converter",
			"api request converter",
			"curl command converter",
			"fetch api generator",
			"javascript http client",
			"curl to js fetch",
		},
		Features: []string{
			"Convert cURL commands to JavaScript fetch API",
			"Real-time conversion with instant results",
			"Support for all HTTP methods (GET, POST, PUT, DELETE)",
			"Handle headers, authentication, and request bodies",
			"Parse complex cURL command structures",
			"Copy to clipboard functionality",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/curl-to-js-fetch-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/curl-to-js-fetch-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "webp-converter",
		Title:       "WebP Converter - Convert Images to WebP Format | Online Free DevTools by Hexmos",
		Name:        "WebP Converter",
		Path:        "/freedevtools/t/webp-converter/",
		Description: "Convert images to WebP format instantly with our free online converter. Upload JPG, PNG, GIF images and convert to WebP with adjustable quality settings. Batch processing and download support included.",
		Category:    "Developer Tools",
		Icon:        "�️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/webp-converter/",
		Keywords: []string{
			"webp converter",
			"image to webp",
			"convert to webp",
			"webp image converter",
			"jpg to webp",
			"png to webp",
			"gif to webp",
			"webp format converter",
			"image compression webp",
			"batch webp converter",
		},
		Features: []string{
			"Convert images to WebP format instantly",
			"Support for JPG, PNG, GIF, and other image formats",
			"Adjustable quality settings for optimal compression",
			"Batch processing for multiple images",
			"Real-time file size comparison",
			"Download converted images individually or as ZIP",
			"Browser-based processing - images never leave your device",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/webp-converter-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/webp-converter-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "qrcode-generator",
		Title:       "QR Code Generator - Create QR Codes Online | Online Free DevTools by Hexmos",
		Name:        "QR Code Generator",
		Path:        "/freedevtools/t/qrcode-generator/",
		Description: "Generate QR codes instantly with our free online QR code generator. Create customizable QR codes for URLs, text, contact info, and more with adjustable error correction and scale settings.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/qrcode-generator/",
		Keywords: []string{
			"qr code generator",
			"qr code maker",
			"qr code creator",
			"generate qr code",
			"free qr code generator",
			"online qr code",
			"qr code tool",
			"qr scanner code",
			"custom qr code",
			"qr code download",
		},
		Features: []string{
			"Generate QR codes for text, URLs, and contact information",
			"Adjustable error correction levels (Low, Medium, Quartile, High)",
			"Customizable scale and size options",
			"Download QR codes as PNG images",
			"Real-time QR code preview",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/qrcode-generator-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/qrcode-generator-banner.png",
		DatePublished:   "2025-01-17",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "faker",
		Title:       "Fake Data Generator - Generate Mock Data Online | Online Free DevTools by Hexmos",
		Name:        "Fake Data Generator",
		Path:        "/freedevtools/t/faker/",
		Description: "Generate realistic fake data instantly with our free online fake data generator. Create mock JSON, CSV, SQL data with customizable fields for testing, development, and prototyping.",
		Category:    "Developer Tools",
		Icon:        "🎲",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/faker/",
		Keywords: []string{
			"fake data generator",
			"mock data generator",
			"test data generator",
			"fake json generator",
			"mock csv data",
			"fake sql data",
			"dummy data generator",
			"test data creation",
			"mock api data",
			"faker js online",
		},
		Features: []string{
			"Generate realistic fake data with Faker.js",
			"Support for JSON, CSV, SQL, and YAML formats",
			"Customizable field types and categories",
			"Bulk data generation with adjustable row counts",
			"Real-time data preview and generation",
			"Copy to clipboard functionality",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/faker-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/faker-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "cron-tester",
		Title:       "Cron Expression Tester - Test & Validate Cron Jobs Online | Online Free DevTools by Hexmos",
		Name:        "Cron Expression Tester",
		Path:        "/freedevtools/t/cron-tester/",
		Description: "Test and validate cron expressions instantly with our free online cron tester. Parse cron jobs, validate syntax, see next execution times, and understand cron patterns with real-time feedback.",
		Category:    "Developer Tools",
		Icon:        "⏰",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/cron-tester/",
		Keywords: []string{
			"cron tester",
			"cron expression validator",
			"cron job tester",
			"cron parser online",
			"validate cron expression",
			"cron schedule tester",
			"cron syntax checker",
			"cron calculator",
			"test cron job",
			"cron expression generator",
		},
		Features: []string{
			"Test and validate cron expressions in real-time",
			"Parse cron syntax with detailed explanations",
			"Show next execution times with countdown",
			"Generate random cron expressions for testing",
			"Human-readable cron descriptions",
			"Support for standard 5-field cron format",
			"Browser-based processing - expressions never leave your device",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/cron-tester-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/cron-tester-banner.png",
		DatePublished:   "2025-01-16",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "xml-formatter",
		Title:       "XML Formatter - Format & Beautify XML Online | Online Free DevTools by Hexmos",
		Name:        "XML Formatter",
		Path:        "/freedevtools/t/xml-formatter/",
		Description: "Format and beautify XML documents instantly with our free online XML formatter. Validate XML syntax, customize indentation, and fix malformed XML with real-time formatting and error detection.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#f97316",
		Canonical:   "https://hexmos.com/freedevtools/t/xml-formatter/",
		Keywords: []string{
			"xml formatter",
			"xml beautifier",
			"xml prettifier",
			"format xml online",
			"xml validator",
			"xml syntax checker",
			"xml minifier",
			"xml parser",
			"beautify xml",
			"xml code formatter",
			"xml pretty print",
			"fix xml format",
			"xml indentation tool",
			"online xml editor",
			"xml structure formatter",
		},
		Features: []string{
			"Format and beautify XML documents instantly",
			"Real-time XML validation and syntax checking",
			"Customizable indentation options (spaces or tabs)",
			"XML minification for optimized file sizes",
			"Error detection with detailed error messages",
			"Copy formatted XML to clipboard",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/xml-formatter-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/xml-formatter-banner.png",
		DatePublished:   "2025-01-17",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "chmod-calculator",
		Title:       "Chmod Calculator - Unix File Permissions Calculator | Online Free DevTools by Hexmos",
		Name:        "Chmod Calculator",
		Path:        "/freedevtools/t/chmod-calculator/",
		Description: "Calculate Unix file permissions instantly with our free online chmod calculator. Convert between octal, symbolic, and human-readable formats with real-time permission preview and command generation.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#059669",
		Canonical:   "https://hexmos.com/freedevtools/t/chmod-calculator/",
		Keywords: []string{
			"chmod calculator",
			"unix permissions calculator",
			"file permissions calculator",
			"chmod octal calculator",
			"chmod symbolic calculator",
			"linux permissions",
			"unix file permissions",
			"chmod command generator",
			"file permission converter",
			"octal to symbolic permissions",
			"chmod 755 calculator",
			"unix security calculator",
			"file mode calculator",
			"linux chmod tool",
			"permission bits calculator",
		},
		Features: []string{
			"Interactive permission matrix with checkboxes",
			"Real-time octal and symbolic notation conversion",
			"Generate ready-to-use chmod commands",
			"Visual permission representation for owner, group, and public",
			"Copy chmod commands to clipboard",
			"Mobile-responsive permission interface",
			"Browser-based calculation - no server required",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/chmod-calculator-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/chmod-calculator-banner.png",
		DatePublished:   "2025-01-17",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "user-agent-parser",
		Title:       "User Agent Parser - Analyze Browser & Device Info | Online Free DevTools by Hexmos",
		Name:        "User Agent Parser",
		Path:        "/freedevtools/t/user-agent-parser/",
		Description: "Parse and analyze user agent strings instantly with our free online user agent parser. Extract browser, operating system, device, engine, and CPU architecture information with detailed breakdown and real-time analysis.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#8b5cf6",
		Canonical:   "https://hexmos.com/freedevtools/t/user-agent-parser/",
		Keywords: []string{
			"user agent parser",
			"user agent analyzer",
			"browser detection",
			"device detection",
			"operating system detection",
			"user agent string parser",
			"browser identification",
			"mobile device detection",
			"user agent decoder",
			"browser fingerprinting",
			"web analytics tool",
			"http user agent",
			"ua parser online",
			"browser version detector",
			"device type analyzer",
		},
		Features: []string{
			"Parse user agent strings with detailed breakdown",
			"Extract browser name, version, and engine information",
			"Detect operating system and version details",
			"Identify device type, model, and vendor",
			"Analyze CPU architecture information",
			"Auto-populate with current browser user agent",
			"Browser-based parsing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/user-agent-parser-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/user-agent-parser-banner.png",
		DatePublished:   "2025-01-17",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "mac-address-generator",
		Title:       "MAC Address Generator - Generate Random MAC Addresses | Online Free DevTools by Hexmos",
		Name:        "MAC Address Generator",
		Path:        "/freedevtools/t/mac-address-generator/",
		Description: "Generate random MAC addresses instantly with our free online MAC address generator. Create custom MAC addresses with prefix, separator, and case options for testing and development.",
		Category:    "Developer Tools",
		Icon:        "🌐",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/mac-address-generator/",
		Keywords: []string{
			"mac address generator",
			"random mac address",
			"generate mac address",
			"mac address creator",
			"fake mac address",
			"mac address maker",
			"network mac generator",
			"ethernet address generator",
			"mac address tool",
			"bulk mac generator",
		},
		Features: []string{
			"Generate random MAC addresses with custom prefix",
			"Bulk generation up to 100 MAC addresses",
			"Multiple separator options (colon, dash, dot, none)",
			"Uppercase and lowercase output formats",
			"Real-time MAC address generation",
			"Copy to clipboard functionality",
			"Browser-based processing - data stays private",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/mac-address-generator-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/mac-address-generator-banner.png",
		DatePublished:   "2025-01-17",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "mac-address-lookup",
		Title:       "MAC Address Lookup - Find Vendor & Device Info | Online Free DevTools by Hexmos",
		Name:        "MAC Address Lookup",
		Path:        "/freedevtools/t/mac-address-lookup/",
		Description: "Lookup MAC address vendor information instantly with our free online MAC address lookup tool. Identify device manufacturer, organization, and network details from MAC addresses.",
		Category:    "Developer Tools",
		Icon:        "�",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/mac-address-lookup/",
		Keywords: []string{
			"mac address lookup",
			"mac address vendor lookup",
			"mac address checker",
			"device manufacturer lookup",
			"oui lookup",
			"ethernet address lookup",
			"network device identifier",
			"mac vendor database",
			"device identification tool",
			"hardware vendor lookup",
		},
		Features: []string{
			"Lookup MAC address vendor information instantly",
			"Identify device manufacturer and organization",
			"Support for all MAC address formats (colon, dash, dot)",
			"Real-time vendor database lookup",
			"Copy vendor information to clipboard",
			"Browser-based processing - data stays private",
			"Support for partial MAC address lookup",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/mac-address-lookup-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/mac-address-lookup-banner.png",
		DatePublished:   "2025-01-17",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "deepseek-token-counter",
		Title:       "Deepseek Token Counter - Count Tokens for Deepseek Models | Online Free DevTools by Hexmos",
		Name:        "Deepseek Token Counter",
		Path:        "/freedevtools/t/deepseek-token-counter/",
		Description: "Count tokens instantly for Deepseek models with Deepseek Token Counter by Hexmos. Get accurate token counts for Deepseek V2, Coder, and LLM models.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/deepseek-token-counter/",
		Keywords: []string{
			"deepseek token counter",
			"deepseek model token calculator",
			"deepseek v2 token counter",
			"deepseek coder token counter",
			"deepseek llm token counter",
			"token count deepseek",
			"ai token counter",
			"context limit deepseek",
			"prompt token calculator",
			"developer tools",
			"api token counter",
			"online token counter",
		},
		Features: []string{
			"Count tokens for Deepseek V2, Coder, and LLM models",
			"Real-time token calculation using official Deepseek tokenizers",
			"Context limit tracking and usage percentage calculation",
			"Browser-based processing - your data stays private",
			"Educational content and optimization tips for Deepseek usage",
			"Copy token count and details to clipboard",
			"Video guide on Deepseek tokenization",
			"Links to official Deepseek resources and documentation",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/deepseek-token-counter-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/deepseek-token-counter-banner.png",
		DatePublished:   "2025-09-20",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "llama-token-counter",
		Title:       "Llama Token Counter - Count Tokens for Meta Llama Models | Online Free DevTools by Hexmos",
		Name:        "Llama Token Counter",
		Path:        "/freedevtools/t/llama-token-counter/",
		Description: "Count tokens instantly for Meta Llama models with Llama Token Counter by Hexmos. Get accurate token counts for Llama 3 and Llama 2 models.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/llama-token-counter/",
		Keywords: []string{
			"llama token counter",
			"meta llama token calculator",
			"llama 3 token counter",
			"llama 2 token counter",
			"token count llama",
			"ai token counter",
			"context limit llama",
			"prompt token calculator",
			"developer tools",
			"api token counter",
			"online token counter",
		},
		Features: []string{
			"Count tokens for Llama 3 and Llama 2 models",
			"Real-time token calculation using official Llama tokenizers",
			"Context limit tracking and usage percentage calculation",
			"Browser-based processing - your data stays private",
			"Educational content and optimization tips for Llama usage",
			"Copy token count and details to clipboard",
			"Video guide on Llama tokenization",
			"Links to official Meta Llama resources and documentation",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/llama-token-counter-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/llama-token-counter-banner.png",
		DatePublished:   "2025-09-20",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "openai-cost-calculator",
		Title:       "OpenAI Cost Calculator - Estimate API Pricing for GPT Models | Online Free DevTools by Hexmos",
		Name:        "OpenAI Cost Calculator",
		Path:        "/freedevtools/t/openai-cost-calculator/",
		Description: "Estimate API costs for all OpenAI models with OpenAI Cost Calculator by Hexmos. Enter input tokens, output tokens, and API calls to see dynamic pricing for GPT-4, GPT-4o, GPT-5, o1, o3, and more.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/openai-cost-calculator/",
		Keywords: []string{
			"openai cost calculator",
			"gpt pricing calculator",
			"openai api cost estimator",
			"gpt-4 cost calculator",
			"gpt-5 cost calculator",
			"openai token pricing",
			"api token cost",
			"developer tools",
			"online cost calculator",
			"openai pricing tool",
		},
		Features: []string{
			"Estimate costs for all OpenAI models (GPT-4, GPT-4o, GPT-5, o1, o3)",
			"Dynamic pricing table based on user input",
			"Real-time cost calculation for input/output tokens and API calls",
			"Browser-based processing - your data stays private",
			"Educational content and optimization tips for OpenAI usage",
			"Copy cost details to clipboard",
			"Video guide on OpenAI pricing",
			"Links to official OpenAI resources and documentation",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/openai-cost-calculator-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/openai-cost-calculator-banner.png",
		DatePublished:   "2025-09-20",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "character-count",
		Title:       "Character Count Tool - Count Characters, Words, Lines & Bytes | Online Free DevTools by Hexmos",
		Name:        "Character Count",
		Path:        "/freedevtools/t/character-count/",
		Description: "Count characters, words, lines, and byte size instantly with Character Count Tool by Hexmos. Enter your text and get real-time statistics for code, documents, and more. Estimate API costs for all models based on your input.",
		Category:    "Developer Tools",
		Icon:        "🔢",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/character-count/",
		Keywords: []string{
			"character count",
			"word count",
			"line count",
			"byte size calculator",
			"text statistics",
			"developer tools",
			"api cost calculator",
			"online character counter",
			"free character count tool",
		},
		Features: []string{
			"Count characters, words, lines, and bytes in real-time",
			"Estimate API costs for all models based on input",
			"Mobile responsive interface",
			"Copy statistics to clipboard",
			"Browser-based processing - your data stays private",
			"Video guide on character counting",
			"Links to official documentation and resources",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/character-count-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/character-count-banner.png",
		DatePublished:   "2025-09-21",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "slugify-string",
		Title:       "Slugify String Tool - Convert Text to URL Slug | Online Free DevTools by Hexmos",
		Name:        "Slugify String",
		Path:        "/freedevtools/t/slugify-string/",
		Description: "Convert any string to a clean, URL-friendly slug instantly with Slugify String Tool by Hexmos. Enter your text and get a slugified output for SEO, file names, and web development.",
		Category:    "Developer Tools",
		Icon:        "🔤",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/slugify-string/",
		Keywords: []string{
			"slugify string",
			"url slug generator",
			"slug converter",
			"seo slug tool",
			"text to slug",
			"developer tools",
			"online slugify",
			"free slugify tool",
			"slugify utility",
		},
		Features: []string{
			"Convert any string to a URL-friendly slug",
			"Real-time slug generation",
			"Copy slug to clipboard",
			"Mobile responsive interface",
			"Browser-based processing - your data stays private",
			"Video guide on slugification",
			"Links to official documentation and resources",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/slugify-string-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/slugify-string-banner.png",
		DatePublished:   "2025-09-21",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "og-meta-generator",
		Title:       "Open Graph Meta Tag Generator - Create OG & Twitter Meta Tags | Online Free DevTools by Hexmos",
		Name:        "Og Meta Generator",
		Path:        "/freedevtools/t/og-meta-generator/",
		Description: "Generate Open Graph and Twitter meta tags instantly with Og Meta Generator by Hexmos. Customize page type, title, description, image, and more for perfect social sharing and SEO.",
		Category:    "Developer Tools",
		Icon:        "🔖",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/og-meta-generator/",
		Keywords: []string{
			"open graph meta generator",
			"og meta tag generator",
			"twitter meta tag generator",
			"meta tag generator",
			"seo meta tags",
			"social media meta tags",
			"developer tools",
			"online meta tag generator",
			"free og meta tool",
		},
		Features: []string{
			"Generate Open Graph and Twitter meta tags",
			"Customize page type, title, description, image, and more",
			"Copy meta tags to clipboard",
			"Mobile responsive interface",
			"Browser-based processing - your data stays private",
			"Video guide on meta tag generation",
			"Links to official documentation and resources",
		},
		OgImage:         "https://hexmos.com/freedevtools/t/tool-banners/og-meta-generator-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/t/tool-banners/og-meta-generator-banner.png",
		DatePublished:   "2025-09-21",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "yaml-to-toml",
		Title:       "YAML to TOML Converter - Transform YAML to TOML Online | Free DevTools by Hexmos",
		Name:        "YAML to TOML Converter",
		Path:        "/freedevtools/t/yaml-to-toml/",
		Description: "Convert YAML to TOML format instantly with YAML to TOML Converter by Hexmos. Paste your YAML and get valid TOML output for configuration files, development, and deployment.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/yaml-to-toml/",
		Keywords: []string{
			"yaml to toml converter",
			"convert yaml to toml",
			"yaml toml online",
			"toml generator",
			"yaml config converter",
			"developer tools",
			"online yaml to toml",
			"free yaml toml tool",
			"yaml to toml transformation",
		},
		Features: []string{
			"Convert YAML to TOML instantly",
			"Paste YAML and get valid TOML output",
			"Copy TOML to clipboard",
			"Mobile responsive interface",
			"Browser-based processing - your data stays private",
			"Video guide on YAML and TOML conversion",
			"Links to official documentation and resources",
		},
		OgImage:         "https://hexmos.com/freedevtools/t/tool-banners/yaml-to-toml-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/t/tool-banners/yaml-to-toml-banner.png",
		DatePublished:   "2025-09-21",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "svg-placeholder-generator",
		Title:       "SVG Placeholder Generator - Create Custom SVG Placeholders Online | Free DevTools by Hexmos",
		Name:        "SVG Placeholder Generator",
		Path:        "/freedevtools/t/svg-placeholder-generator/",
		Description: "Generate custom SVG placeholder images instantly with SVG Placeholder Generator by Hexmos. Set width, height, background, text color, font size, and custom text for responsive design and rapid prototyping.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/svg-placeholder-generator/",
		Keywords: []string{
			"svg placeholder generator",
			"svg image generator",
			"svg placeholder",
			"custom svg generator",
			"responsive svg",
			"svg for prototyping",
			"svg design tool",
			"svg image creator",
			"svg mockup",
			"developer tools",
		},
		Features: []string{
			"Generate custom SVG placeholders with adjustable size and colors",
			"Set width, height, background, text color, and font size",
			"Add custom text or use default dimensions",
			"Copy SVG code or Base64 string to clipboard",
			"Download SVG image instantly",
			"Mobile responsive and browser-based processing",
			"Dynamic cost table for all models",
			"Video guide for SVG placeholder usage",
		},
		OgImage:         "https://hexmos.com/freedevtools/t/tool-banners/svg-placeholder-generator-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/t/tool-banners/svg-placeholder-generator-banner.png",
		DatePublished:   "2025-09-21",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "rsa-key-pair-generator",
		Title:       "RSA Key Pair Generator - Securely Generate RSA Keys | Online Free DevTools by Hexmos",
		Name:        "RSA Key Pair Generator",
		Path:        "/freedevtools/t/rsa-key-pair-generator/",
		Description: "Generate secure RSA public and private key pairs for encryption, decryption, and digital signatures. Choose your key size and generate keys instantly in your browser.",
		Category:    "Security Tools",
		Icon:        "🔐",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/rsa-key-pair-generator/",
		Keywords: []string{
			"rsa key pair generator",
			"rsa generator",
			"public key generator",
			"private key generator",
			"asymmetric key generator",
			"encryption key generator",
			"security tools",
		},
		Features: []string{
			"Generate RSA public and private keys",
			"Select key size (2048 or 4096 bits)",
			"Secure client-side key generation",
			"Copy keys to clipboard",
			"PEM format output",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/rsa-key-pair-generator-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/rsa-key-pair-generator-banner.png",
		DatePublished:   "2025-09-22",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "markdown-to-html-converter",
		Title:       "Markdown to HTML Converter - Convert Markdown to HTML | Online Free DevTools by Hexmos",
		Name:        "Markdown to HTML Converter",
		Path:        "/freedevtools/t/markdown-to-html-converter/",
		Description: "Convert Markdown to HTML instantly with this free online tool. See the rendered HTML in real-time as you type.",
		Category:    "Developer Tools",
		Icon:        "✍️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/markdown-to-html-converter/",
		Keywords: []string{
			"markdown to html",
			"md to html",
			"markdown converter",
			"html converter",
			"markdown editor",
			"developer tools",
		},
		Features: []string{
			"Real-time Markdown to HTML conversion",
			"Live preview",
			"Copy HTML to clipboard",
			"Load sample Markdown",
			"Client-side processing",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/markdown-to-html-converter-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/markdown-to-html-converter-banner.png",
		DatePublished:   "2025-09-22",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "html-to-markdown",
		Title:       "HTML to Markdown Converter - Convert HTML to Markdown | Online Free DevTools by Hexmos",
		Name:        "HTML to Markdown Converter",
		Path:        "/freedevtools/t/html-to-markdown/",
		Description: "Convert HTML to Markdown instantly with this free online tool. See the converted Markdown in real-time as you type.",
		Category:    "Developer Tools",
		Icon:        "✍️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/html-to-markdown/",
		Keywords: []string{
			"html to markdown",
			"html to md",
			"html converter",
			"markdown converter",
			"developer tools",
		},
		Features: []string{
			"Real-time HTML to Markdown conversion",
			"Live preview",
			"Copy Markdown to clipboard",
			"Load sample HTML",
			"Client-side processing",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/html-to-markdown-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/html-to-markdown-banner.png",
		DatePublished:   "2025-09-22",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "xml-to-json",
		Title:       "XML to JSON Converter | Online Free DevTools by Hexmos",
		Name:        "XML to JSON",
		Path:        "/freedevtools/t/xml-to-json/",
		Description: "Easily convert XML data to JSON format with our free online XML to JSON Converter. Fast, secure, and accurate conversion for developers and data analysts. No installation required.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/xml-to-json/",
		Keywords: []string{
			"xml-to-json",
			"xml to json converter",
			"online xml to json",
			"developer tools",
			"data conversion",
			"json tools",
			"xml tools",
			"free devtools",
			"Hexmos",
		},
		Features: []string{
			"Instantly convert XML data to JSON format",
			"Supports large and complex XML files",
			"Secure, client-side processing for privacy",
			"Copy, download, or share converted JSON",
			"Syntax highlighting and error detection",
		},
		OgImage:         "https://hexmos.com/freedevtools/public/tool-banners/xml-to-json-banner.png",
		TwitterImage:    "https://hexmos.com/freedevtools/public/tool-banners/xml-to-json-banner.png",
		DatePublished:   "2025-09-23",
		SoftwareVersion: "1.0.0",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "json-to-xml",
		Title:       "JSON to XML Converter | Online Free DevTools by Hexmos",
		Name:        "JSON to XML",
		Path:        "/freedevtools/t/json-to-xml/",
		Description: "Convert JSON data to XML format instantly with our free online JSON to XML Converter. Fast, secure, and accurate conversion for developers and data analysts. No installation required.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/json-to-xml/",
		Keywords: []string{
			"json-to-xml",
			"json to xml converter",
			"online json to xml",
			"developer tools",
			"data conversion",
			"json tools",
			"xml tools",
			"free devtools",
			"Hexmos",
		},
		Features: []string{
			"Instantly convert JSON data to XML format",
			"Handles complex and nested JSON structures",
			"Secure, client-side processing for privacy",
			"Copy, download, or share converted XML",
			"Syntax highlighting and error detection",
		},
		OgImage:        "https://hexmos.com/freedevtools/public/tool-banners/json-to-xml-banner.png",
		TwitterImage:   "https://hexmos.com/freedevtools/public/tool-banners/json-to-xml-banner.png",
		DatePublished:  "2025-09-23",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "zstd-compress",
		Title:       "Zstandard (zstd) Compressor - Compress Files Online | Free DevTools by Hexmos",
		Name:        "Zstandard Compressor",
		Path:        "/freedevtools/t/zstd-compress/",
		Description: "Compress files using Zstandard (zstd) algorithm with our free online Zstd Compressor. Fast, efficient, and secure file compression for developers and users. No installation required.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/zstd-compress/",
		Keywords: []string{
			"zstd compressor",
			"zstandard compress",
			"online zstd compress",
			"file compression",
			"developer tools",
			"data compression",
			"free devtools",
		},
		Features: []string{
			"Compress files using Zstandard (zstd) algorithm",
			"Supports large files and various formats",
			"Secure, client-side processing for privacy",
			"Download compressed .zst files",
			"Fast and efficient compression",
		},
		OgImage:        "https://hexmos.com/freedevtools/public/tool-banners/zstd-compress-banner.png",
		TwitterImage:   "https://hexmos.com/freedevtools/public/tool-banners/zstd-compress-banner.png",
		DatePublished:  "2025-09-23",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
	{
		ID:          "zstd-decompress",
		Title:       "Zstandard (zstd) Decompressor - Decompress Files Online | Free DevTools by Hexmos",
		Name:        "Zstandard Decompressor",
		Path:        "/freedevtools/t/zstd-decompress/",
		Description: "Decompress files using Zstandard (zstd) algorithm with our free online Zstd Decompressor. Fast, efficient, and secure file decompression for developers and users. No installation required.",
		Category:    "Developer Tools",
		Icon:        "🛠️",
		ThemeColor:  "#3b82f6",
		Canonical:   "https://hexmos.com/freedevtools/t/zstd-decompress/",
		Keywords: []string{
			"zstd decompressor",
			"zstandard decompress",
			"online zstd decompress",
			"file decompression",
			"developer tools",
			"data decompression",
			"free devtools",
		},
		Features: []string{
			"Decompress files using Zstandard (zstd) algorithm",
			"Supports large files and various formats",
			"Secure, client-side processing for privacy",
			"Download decompressed files",
			"Fast and efficient decompression",
		},
		OgImage:        "https://hexmos.com/freedevtools/public/tool-banners/zstd-decompress-banner.png",
		TwitterImage:   "https://hexmos.com/freedevtools/public/tool-banners/zstd-decompress-banner.png",
		DatePublished:  "2025-09-23",
		LastModifiedAt: "2025-11-26T15:57:36.329Z",
	},
}

