title: ""
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## Description

  - type: markdown
    attributes:
      value: |
        ## Required Features
  - type: markdown
    attributes:
      value: |
        ## Design Ideas & Reference
        ![screenshot](URL-to-screenshot)
