const fs = require('fs');
const path = require('path');

// Extract chunk names from index.js and generate a Go file
const indexJsPath = path.join(__dirname, '../assets/js/index.js');
const outputPath = path.join(__dirname, '../internal/chunks/chunks.go');

// Ensure output directory exists
const outputDir = path.dirname(outputPath);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

try {
  if (!fs.existsSync(indexJsPath)) {
    console.error(`Error: ${indexJsPath} not found. Run build.js first.`);
    process.exit(1);
  }

  const indexJsContent = fs.readFileSync(indexJsPath, 'utf8');

  // Extract chunk imports: import ... from "./chunks/chunk-XXXXX.js"
  // Handle both minified (no spaces) and unminified code
  const chunkRegex = /from\s*["']\.\/chunks\/(chunk-[A-Z0-9]+\.js)["']/g;
  const chunks = [];
  let match;

  while ((match = chunkRegex.exec(indexJsContent)) !== null) {
    chunks.push(match[1]);
  }

  if (chunks.length === 0) {
    console.warn('Warning: No chunks found in index.js. Code splitting may be disabled.');
  }

  // Generate Go file with chunk names
  const goContent = `package chunks

// GetReactChunks returns the list of React chunk filenames
// This is auto-generated by scripts/extract-chunks.js after build
func GetReactChunks() []string {
	return []string{
${chunks.length > 0 ? chunks.map(chunk => `		"${chunk}",`).join('\n') : '		// No chunks found'}
	}
}
`;

  fs.writeFileSync(outputPath, goContent, 'utf8');
  console.log(`✓ Extracted ${chunks.length} chunks: ${chunks.join(', ')}`);
} catch (error) {
  console.error('Error extracting chunks:', error);
  process.exit(1);
}

