# name: Test Cloudflare Cache Purge

# on:
#   workflow_dispatch:

# jobs:
#   purge_cache:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Purge entire Cloudflare cache
#         run: |
#           echo "Purging entire Cloudflare cache..."
#           RESPONSE=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
#             -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_CACHE_PURGE_API_KEY }}" \
#             -H "Content-Type: application/json" \
#             --data '{"purge_everything":true}')
          
#           echo "Response:"
#           echo "$RESPONSE"